export const doctorsData = [
    {
      id: 1,
      name: "Hà Anh Tuấn",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Răng hàm mặt",
      doctorLv:0,
      doctorCate:"Nội khoa",
      phone: "09.321.123.321",
      email: "haanhtuan123@gmail.com",
      birthDate: "01/01/1999",
      gender: "Nam",
      address: "SQR/312, CVPM Quang Trung, Q12",
      status: "1",
    },
    {
      id: 2,
      name: "Võ Đức Tài",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Tai chân miệng",
      doctorLv:0,
      doctorCate:"Ngoại khoa",
      phone: "09.432.234.432",
      email: "vductai234@gmail.com",
      birthDate: "15/02/1985",
      gender: "Nam",
      address: "Số 21, Đường Nguyễn Tri Phương, Q10",
      status: "1",
    },
    {
      id: 3,
      name: "Trần Thị Mai",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Nội khoa",
      doctorLv:1,
      doctorCate:"Nội khoa",
      phone: "09.543.345.543",
      email: "tranmaimai@gmail.com",
      birthDate: "25/03/1992",
      gender: "Nữ",
      address: "Tòa nhà Central Plaza, Q7",
      status: "0",
    },
    {
      id: 4,
      name: "Nguyễn Văn An",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Sản phụ khoa",
      doctorLv:0,
      doctorCate:"Nội khoa",
      phone: "09.654.456.654",
      email: "nguyenan654@gmail.com",
      birthDate: "30/04/1988",
      gender: "Nam",
      address: "Khu đô thị Phú Mỹ Hưng, Q7",
      status: "1",
    },
    {
      id: 5,
      name: "Lê Thị Yến",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Tim mạch",
      doctorLv:3,
      doctorCate:"Ngoại khoa",
      phone: "09.765.567.765",
      email: "lethiyen765@gmail.com",
      birthDate: "10/05/1989",
      gender: "Nữ",
      address: "Chung cư Skyline, Q2",
      status: "1",
    },
    {
      id: 6,
      name: "Nguyễn Minh Tuấn",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Da liễu",
      doctorLv:0,
      doctorCate:"Nội khoa",
      phone: "09.876.678.876",
      email: "nguyenminhtuan876@gmail.com",
      birthDate: "20/06/1991",
      gender: "Nam",
      address: "Số 56, Đường Lê Lợi, Q1",
      status: "0",
    },
    {
      id: 7,
      name: "Trịnh Văn Hòa",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Y học cổ truyền",
      doctorLv:2,
      doctorCate:"Ngoại khoa",
      phone: "09.987.789.987",
      email: "trinhvanhoa987@gmail.com",
      birthDate: "05/07/1987",
      gender: "Nam",
      address: "Tòa nhà Garden Plaza, Q4",
      status: "1",
    },
    {
      id: 8,
      name: "Hoàng Thị Lan",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Nhi khoa",
      doctorLv:0,
      doctorCate:"Ngoại khoa",
      phone: "09.098.890.098",
      email: "hoangthilan098@gmail.com",
      birthDate: "15/08/1990",
      gender: "Nữ",
      address: "Số 78, Đường Nguyễn Văn Cừ, Q5",
      status: "0",
    },
    {
      id: 9,
      name: "Lương Văn Bình",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Chấn thương chỉnh hình",
      doctorLv:2,
      doctorCate:"Nội khoa",
      phone: "09.109.901.109",
      email: "luongvanbinh109@gmail.com",
      birthDate: "25/09/1986",
      gender: "Nam",
      address: "Khu dân cư An Phú, Q7",
      status: "1",
    },
    {
      id: 10,
      name: "Trương Thị Ngọc",
      avatar: 'https://github.com/shadcn.png',
      specialty: "Hô hấp",
      doctorLv:1,
      doctorCate:"Nội khoa",
      phone: "09.210.012.210",
      email: "truongthinhoc210@gmail.com",
      birthDate: "30/10/1993",
      gender: "Nữ",
      address: "Chung cư Thái Bình, Q3",
      status: "1",
    }
  ];