export const staffsData = [
    {
      id: 2,
      name: "NV.Trần Thị Mai",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.234.432.234",
      email: "tranthimai234@gmail.com",
      birthDate: "05/05/1990",
      gender: "Nữ",
      address: "Tầng 5, Tòa nhà Hưng Phú, Q7",
      status: "1",
    },
    {
      id: 3,
      name: "NV.Lê Văn An",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.345.543.345",
      email: "levanan345@gmail.com",
      birthDate: "10/10/1985",
      gender: "Nam",
      address: "Căn hộ 302, Khu đô thị Nam Thăng Long, Q9",
      status: "0",
    },
    {
      id: 4,
      name: "NV.Nguyễn Thị Hoa",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.456.654.456",
      email: "nguyenhoa456@gmail.com",
      birthDate: "20/12/1992",
      gender: "Nữ",
      address: "Số 12, Đường Nguyễn Huệ, Q1",
      status: "1",
    },
    {
      id: 5,
      name: "NV.Phạm Minh Tuấn",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.567.765.567",
      email: "phamminhtuan567@gmail.com",
      birthDate: "15/03/1988",
      gender: "Nam",
      address: "Tòa nhà Central Park, Q3",
      status: "1",
    },
    {
      id: 6,
      name: "NV.Bùi Thị Lan",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.678.876.678",
      email: "buithilan678@gmail.com",
      birthDate: "25/07/1994",
      gender: "Nữ",
      address: "Số 45, Đường Lê Lợi, Q5",
      status: "0",
    },
    {
      id: 7,
      name: "NV.Trần Văn Phúc",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.789.987.789",
      email: "tranvanphuc789@gmail.com",
      birthDate: "30/08/1982",
      gender: "Nam",
      address: "Khu dân cư Phú Mỹ Hưng, Q7",
      status: "1",
    },
    {
      id: 8,
      name: "NV.Hoàng Thị Bình",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.890.098.890",
      email: "hoangthibinh890@gmail.com",
      birthDate: "12/11/1989",
      gender: "Nữ",
      address: "Tầng 3, Tòa nhà Diamond Plaza, Q1",
      status: "1",
    },
    {
      id: 9,
      name: "NV.Võ Văn Hòa",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.901.109.901",
      email: "vovanhoa901@gmail.com",
      birthDate: "02/02/1995",
      gender: "Nam",
      address: "Căn hộ 405, Chung cư CT1, Q2",
      status: "0",
    },
    {
      id: 10,
      name: "NV.Lương Thị Ngọc",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.012.210.012",
      email: "luongthingoct012@gmail.com",
      birthDate: "18/06/1991",
      gender: "Nữ",
      address: "Số 78, Đường Phan Đăng Lưu, Q3",
      status: "1",
    },
    {
      id: 11,
      name: "NV.Nguyễn Đức Minh",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.123.321.321",
      email: "nguyenducminh123@gmail.com",
      birthDate: "27/09/1987",
      gender: "Nam",
      address: "Tòa nhà An Phú, Q7",
      status: "0",
    },
    {
      id: 12,
      name: "NV.Dương Thị Yến",
      avatar: 'https://github.com/shadcn.png',
      position: "#NV Y Tế",
      phoneNumber: "09.234.432.543",
      email: "duongthiyen234@gmail.com",
      birthDate: "23/04/1993",
      gender: "Nữ",
      address: "Khu biệt thự Thảo Điền, Q2",
      status: "1",
    },
  ];