export const optionsBank = [
    { id: "Vietcombank", name: "Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)" },
    { id: "BIDV", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)" },
    { id: "Techcombank", name: "Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)" },
    { id: "Vietinbank", name: "Ngân hàng TMCP Công thương Việt Nam (Vietinbank)" },
    { id: "Sacombank", name: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)" },
    { id: "ACB", name: "Ngân hàng TMCP Á Châu (ACB)" },
    { id: "MB", name: "Ngân hàng TMCP Quân đội (MB)" },
    { id: "HDBank", name: "Ngân hàng TMCP Phát triển TP.HCM (HDBank)" },
    { id: "VPBank", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)" },
    { id: "Eximbank", name: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam (Eximbank)" },
    { id: "TPBank", name: "Ngân hàng TMCP Tiên Phong (TPBank)" },
    { id: "SeABank", name: "Ngân hàng TMCP Đông Nam Á (SeABank)" },
    { id: "OCB", name: "Ngân hàng TMCP Phương Đông (OCB)" },
    { id: "SHB", name: "Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)" },
    { id: "LienVietPostBank", name: "Ngân hàng TMCP Bưu điện Liên Việt (LienVietPostBank)" },
    { id: "VIB", name: "Ngân hàng TMCP Quốc tế Việt Nam (VIB)" },
    { id: "PVcomBank", name: "Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)" },
    { id: "ABBANK", name: "Ngân hàng TMCP An Bình (ABBANK)" },
    { id: "SCB", name: "Ngân hàng TMCP Sài Gòn (SCB)" },
    { id: "DongABank", name: "Ngân hàng TMCP Đông Á (DongABank)" },
    { id: "NamABank", name: "Ngân hàng TMCP Nam Á (NamABank)" },
    { id: "BacABank", name: "Ngân hàng TMCP Bắc Á (BacABank)" },
    { id: "KienlongBank", name: "Ngân hàng TMCP Kiên Long (KienlongBank)" },
    { id: "VietABank", name: "Ngân hàng TMCP Việt Á (VietABank)" },
    { id: "SaigonBank", name: "Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)" },
    { id: "CIMB", name: "Ngân hàng CIMB Việt Nam (CIMB)" },
    { id: "UOB", name: "Ngân hàng UOB Việt Nam (UOB)" },
    { id: "StandardChartered", name: "Ngân hàng Standard Chartered Việt Nam (Standard Chartered)" },
    { id: "HongLeong", name: "Ngân hàng Hong Leong Việt Nam (Hong Leong)" },
    { id: "HSBC", name: "Ngân hàng HSBC Việt Nam (HSBC)" },
    { id: "Citibank", name: "Ngân hàng Citibank Việt Nam (Citibank)" },
    { id: "ShinhanBank", name: "Ngân hàng Shinhan Việt Nam (ShinhanBank)" },
    { id: "PublicBank", name: "Ngân hàng Public Bank Việt Nam (PublicBank)" },
    { id: "ANZ", name: "Ngân hàng ANZ Việt Nam (ANZ)" },
    { id: "WooriBank", name: "Ngân hàng Woori Việt Nam (WooriBank)" },
    { id: "IBK", name: "Ngân hàng Công nghiệp Hàn Quốc (IBK)" },
    { id: "Agribank", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)" },
    { id: "OceanBank", name: "Ngân hàng TMCP Đại Dương (OceanBank)" },
    { id: "GPBank", name: "Ngân hàng TMCP Dầu Khí Toàn Cầu (GPBank)" },
    { id: "VDB", name: "Ngân hàng Phát triển Việt Nam (VDB)" },
    { id: "VBSP", name: "Ngân hàng Chính sách Xã hội Việt Nam (VBSP)" },
  ];
  